/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "ho.v:9" *)
module uart_rx_top(clock, resetn, rx, led_fix, led_touch);
  (* src = "ho.v:77" *)
  wire [13:0] _000_;
  (* src = "ho.v:90" *)
  wire [2:0] _001_;
  (* src = "ho.v:108" *)
  wire _002_;
  (* src = "ho.v:108" *)
  wire _003_;
  (* src = "ho.v:97" *)
  wire [7:0] _004_;
  (* src = "ho.v:47" *)
  wire _005_;
  (* src = "ho.v:56" *)
  wire [1:0] _006_;
  (* src = "ho.v:35" *)
  wire _007_;
  (* src = "ho.v:35" *)
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  (* src = "ho.v:77" *)
  wire _157_;
  (* src = "ho.v:77" *)
  wire _158_;
  (* src = "ho.v:77" *)
  wire _159_;
  (* src = "ho.v:77" *)
  wire _160_;
  (* src = "ho.v:77" *)
  wire _161_;
  (* src = "ho.v:77" *)
  wire _162_;
  (* src = "ho.v:77" *)
  wire _163_;
  (* src = "ho.v:77" *)
  wire _164_;
  (* src = "ho.v:77" *)
  wire _165_;
  (* src = "ho.v:77" *)
  wire _166_;
  (* src = "ho.v:77" *)
  wire _167_;
  (* src = "ho.v:77" *)
  wire _168_;
  (* src = "ho.v:77" *)
  wire _169_;
  (* src = "ho.v:77" *)
  wire _170_;
  (* src = "ho.v:90" *)
  wire _171_;
  (* src = "ho.v:90" *)
  wire _172_;
  (* src = "ho.v:90" *)
  wire _173_;
  (* src = "ho.v:108" *)
  wire _174_;
  (* src = "ho.v:108" *)
  wire _175_;
  (* src = "ho.v:97" *)
  wire _176_;
  (* src = "ho.v:97" *)
  wire _177_;
  (* src = "ho.v:97" *)
  wire _178_;
  (* src = "ho.v:97" *)
  wire _179_;
  (* src = "ho.v:97" *)
  wire _180_;
  (* src = "ho.v:97" *)
  wire _181_;
  (* src = "ho.v:97" *)
  wire _182_;
  (* src = "ho.v:97" *)
  wire _183_;
  (* src = "ho.v:47" *)
  wire _184_;
  (* src = "ho.v:56" *)
  wire _185_;
  (* src = "ho.v:56" *)
  wire _186_;
  (* src = "ho.v:35" *)
  wire _187_;
  (* src = "ho.v:35" *)
  wire _188_;
  (* src = "ho.v:19" *)
  wire _189_;
  (* src = "ho.v:19" *)
  wire _190_;
  (* src = "ho.v:19" *)
  wire _191_;
  (* src = "ho.v:19" *)
  wire _192_;
  (* src = "ho.v:19" *)
  wire _193_;
  (* src = "ho.v:19" *)
  wire _194_;
  (* src = "ho.v:19" *)
  wire _195_;
  (* src = "ho.v:19" *)
  wire _196_;
  (* src = "ho.v:19" *)
  wire _197_;
  (* src = "ho.v:19" *)
  wire _198_;
  (* src = "ho.v:19" *)
  wire _199_;
  (* src = "ho.v:19" *)
  wire _200_;
  (* src = "ho.v:19" *)
  wire _201_;
  (* src = "ho.v:19" *)
  wire _202_;
  (* src = "ho.v:24" *)
  wire _203_;
  (* src = "ho.v:24" *)
  wire _204_;
  (* src = "ho.v:24" *)
  wire _205_;
  (* src = "ho.v:14" *)
  wire _206_;
  (* src = "ho.v:15" *)
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  (* src = "ho.v:23" *)
  wire _287_;
  (* src = "ho.v:23" *)
  wire _288_;
  (* src = "ho.v:23" *)
  wire _289_;
  (* src = "ho.v:23" *)
  wire _290_;
  (* src = "ho.v:23" *)
  wire _291_;
  (* src = "ho.v:23" *)
  wire _292_;
  (* src = "ho.v:23" *)
  wire _293_;
  (* src = "ho.v:23" *)
  wire _294_;
  (* src = "ho.v:11" *)
  wire _295_;
  (* src = "ho.v:12" *)
  wire _296_;
  (* src = "ho.v:21" *)
  wire _297_;
  (* src = "ho.v:22" *)
  wire _298_;
  (* src = "ho.v:22" *)
  wire _299_;
  (* src = "ho.v:20" *)
  wire _300_;
  (* src = "ho.v:20" *)
  wire _301_;
  (* src = "ho.v:10" *)
  input clock;
  (* src = "ho.v:19" *)
  wire [13:0] counter;
  (* src = "ho.v:24" *)
  wire [2:0] data_cnt;
  (* src = "ho.v:14" *)
  output led_fix;
  (* src = "ho.v:15" *)
  output led_touch;
  (* src = "ho.v:23" *)
  wire [7:0] rdat;
  (* src = "ho.v:11" *)
  input resetn;
  (* src = "ho.v:12" *)
  input rx;
  (* src = "ho.v:21" *)
  wire rx_;
  (* src = "ho.v:22" *)
  wire [1:0] state;
  (* src = "ho.v:20" *)
  wire syncff0;
  (* src = "ho.v:20" *)
  wire syncff1;
  sky130_fd_sc_hd__clkinv_1 _302_ (
    .A(_293_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__clkinv_1 _303_ (
    .A(_294_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__clkinv_1 _304_ (
    .A(_203_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nand2b_1 _305_ (
    .A_N(_298_),
    .B(_299_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nor4b_1 _306_ (
    .A(_191_),
    .B(_190_),
    .C(_193_),
    .D_N(_192_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__nor4b_1 _307_ (
    .A(_194_),
    .B(_189_),
    .C(_199_),
    .D_N(_200_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__nor4b_1 _308_ (
    .A(_194_),
    .B(_189_),
    .C(_196_),
    .D_N(_195_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__and4b_1 _309_ (
    .A_N(_197_),
    .B(_198_),
    .C(_202_),
    .D(_201_),
    .X(_275_)
  );
  sky130_fd_sc_hd__nor3b_1 _310_ (
    .A(_271_),
    .B(_199_),
    .C_N(_200_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nand4_1 _311_ (
    .A(_272_),
    .B(_274_),
    .C(_275_),
    .D(_276_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__o21ai_0 _312_ (
    .A1(_288_),
    .A2(_277_),
    .B1(_295_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__a21oi_1 _313_ (
    .A1(_263_),
    .A2(_277_),
    .B1(_278_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__o21ai_0 _314_ (
    .A1(_289_),
    .A2(_277_),
    .B1(_295_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__a21oi_1 _315_ (
    .A1(_262_),
    .A2(_277_),
    .B1(_279_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__o21ai_0 _316_ (
    .A1(_290_),
    .A2(_277_),
    .B1(_295_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__a21oi_1 _317_ (
    .A1(_264_),
    .A2(_277_),
    .B1(_280_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__o21ai_0 _318_ (
    .A1(_291_),
    .A2(_277_),
    .B1(_295_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__a21oi_1 _319_ (
    .A1(_265_),
    .A2(_277_),
    .B1(_281_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__o21ai_0 _320_ (
    .A1(_292_),
    .A2(_277_),
    .B1(_295_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(_266_),
    .A2(_277_),
    .B1(_282_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__o21ai_0 _322_ (
    .A1(_293_),
    .A2(_277_),
    .B1(_295_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__a21oi_1 _323_ (
    .A1(_267_),
    .A2(_277_),
    .B1(_283_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__o21ai_0 _324_ (
    .A1(_294_),
    .A2(_277_),
    .B1(_295_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__a21oi_1 _325_ (
    .A1(_268_),
    .A2(_277_),
    .B1(_284_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__o21ai_0 _326_ (
    .A1(_301_),
    .A2(_277_),
    .B1(_295_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__a21oi_1 _327_ (
    .A1(_269_),
    .A2(_277_),
    .B1(_285_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__and2_0 _328_ (
    .A(_197_),
    .B(_198_),
    .X(_286_)
  );
  sky130_fd_sc_hd__nor4_1 _329_ (
    .A(_196_),
    .B(_195_),
    .C(_202_),
    .D(_201_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nor4bb_1 _330_ (
    .A(_190_),
    .B(_192_),
    .C_N(_193_),
    .D_N(_191_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__and4_1 _331_ (
    .A(_273_),
    .B(_286_),
    .C(_208_),
    .D(_209_),
    .X(_210_)
  );
  sky130_fd_sc_hd__nand4_1 _332_ (
    .A(_273_),
    .B(_286_),
    .C(_208_),
    .D(_209_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o21ai_0 _333_ (
    .A1(_271_),
    .A2(_211_),
    .B1(_270_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(_295_),
    .B(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor3_1 _335_ (
    .A(_270_),
    .B(_271_),
    .C(_211_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor2_1 _336_ (
    .A(_213_),
    .B(_214_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__o21ai_0 _337_ (
    .A1(_204_),
    .A2(_214_),
    .B1(_295_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__a21oi_1 _338_ (
    .A1(_204_),
    .A2(_214_),
    .B1(_215_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _339_ (
    .A1(_204_),
    .A2(_214_),
    .B1(_205_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand3_1 _340_ (
    .A(_204_),
    .B(_205_),
    .C(_214_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__and3b_1 _341_ (
    .A_N(_216_),
    .B(_217_),
    .C(_295_),
    .X(_173_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(_298_),
    .B(_299_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__o21ai_0 _343_ (
    .A1(_211_),
    .A2(_218_),
    .B1(_295_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nor3_1 _344_ (
    .A(_298_),
    .B(_299_),
    .C(_189_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nor2b_1 _345_ (
    .A(_218_),
    .B_N(_189_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nor3_1 _346_ (
    .A(_219_),
    .B(_220_),
    .C(_221_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o211a_1 _347_ (
    .A1(_298_),
    .A2(_299_),
    .B1(_194_),
    .C1(_189_),
    .X(_222_)
  );
  sky130_fd_sc_hd__o21ai_0 _348_ (
    .A1(_194_),
    .A2(_221_),
    .B1(_295_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(_222_),
    .B(_223_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__and2_0 _350_ (
    .A(_195_),
    .B(_222_),
    .X(_224_)
  );
  sky130_fd_sc_hd__o21ai_0 _351_ (
    .A1(_195_),
    .A2(_222_),
    .B1(_295_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nor2_1 _352_ (
    .A(_224_),
    .B(_225_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__and3_1 _353_ (
    .A(_196_),
    .B(_195_),
    .C(_222_),
    .X(_226_)
  );
  sky130_fd_sc_hd__o21ai_0 _354_ (
    .A1(_196_),
    .A2(_224_),
    .B1(_295_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(_226_),
    .B(_227_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__xnor2_1 _356_ (
    .A(_197_),
    .B(_226_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor2_1 _357_ (
    .A(_219_),
    .B(_228_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__and2_0 _358_ (
    .A(_286_),
    .B(_226_),
    .X(_229_)
  );
  sky130_fd_sc_hd__a21oi_1 _359_ (
    .A1(_197_),
    .A2(_226_),
    .B1(_198_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__nor3_1 _360_ (
    .A(_219_),
    .B(_229_),
    .C(_230_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__and3_1 _361_ (
    .A(_199_),
    .B(_286_),
    .C(_226_),
    .X(_231_)
  );
  sky130_fd_sc_hd__o21ai_0 _362_ (
    .A1(_199_),
    .A2(_229_),
    .B1(_295_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nor2_1 _363_ (
    .A(_231_),
    .B(_232_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__and4_1 _364_ (
    .A(_199_),
    .B(_200_),
    .C(_286_),
    .D(_226_),
    .X(_233_)
  );
  sky130_fd_sc_hd__nor2_1 _365_ (
    .A(_200_),
    .B(_231_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nor3_1 _366_ (
    .A(_219_),
    .B(_233_),
    .C(_234_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__o21ai_0 _367_ (
    .A1(_201_),
    .A2(_233_),
    .B1(_295_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__a21oi_1 _368_ (
    .A1(_201_),
    .A2(_233_),
    .B1(_235_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a21oi_1 _369_ (
    .A1(_201_),
    .A2(_233_),
    .B1(_202_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__and3_1 _370_ (
    .A(_200_),
    .B(_202_),
    .C(_201_),
    .X(_237_)
  );
  sky130_fd_sc_hd__and3_1 _371_ (
    .A(_199_),
    .B(_286_),
    .C(_237_),
    .X(_238_)
  );
  sky130_fd_sc_hd__and2_0 _372_ (
    .A(_226_),
    .B(_238_),
    .X(_239_)
  );
  sky130_fd_sc_hd__nor3b_1 _373_ (
    .A(_236_),
    .B(_239_),
    .C_N(_295_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o21ai_0 _374_ (
    .A1(_190_),
    .A2(_239_),
    .B1(_295_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__a21oi_1 _375_ (
    .A1(_190_),
    .A2(_239_),
    .B1(_240_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a31oi_1 _376_ (
    .A1(_190_),
    .A2(_226_),
    .A3(_238_),
    .B1(_191_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__and4_1 _377_ (
    .A(_191_),
    .B(_190_),
    .C(_226_),
    .D(_238_),
    .X(_242_)
  );
  sky130_fd_sc_hd__nor3_1 _378_ (
    .A(_219_),
    .B(_241_),
    .C(_242_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o21ai_0 _379_ (
    .A1(_192_),
    .A2(_242_),
    .B1(_295_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__a21oi_1 _380_ (
    .A1(_192_),
    .A2(_242_),
    .B1(_243_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21o_1 _381_ (
    .A1(_192_),
    .A2(_242_),
    .B1(_193_),
    .X(_244_)
  );
  sky130_fd_sc_hd__nand3_1 _382_ (
    .A(_193_),
    .B(_192_),
    .C(_242_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__and3b_1 _383_ (
    .A_N(_219_),
    .B(_244_),
    .C(_245_),
    .X(_161_)
  );
  sky130_fd_sc_hd__nand2b_1 _384_ (
    .A_N(_296_),
    .B(_295_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nor3_1 _385_ (
    .A(_298_),
    .B(_299_),
    .C(_301_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__a22oi_1 _386_ (
    .A1(_298_),
    .A2(_211_),
    .B1(_246_),
    .B2(_297_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__a21boi_0 _387_ (
    .A1(_217_),
    .A2(_247_),
    .B1_N(_295_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a21oi_1 _388_ (
    .A1(_298_),
    .A2(_210_),
    .B1(_299_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nand3_1 _389_ (
    .A(_298_),
    .B(_299_),
    .C(_210_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__nand2_1 _390_ (
    .A(_295_),
    .B(_249_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nor2_1 _391_ (
    .A(_248_),
    .B(_250_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nand2b_1 _392_ (
    .A_N(_301_),
    .B(_295_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand2b_1 _393_ (
    .A_N(_300_),
    .B(_295_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _394_ (
    .A(_289_),
    .B(_291_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nor2b_1 _395_ (
    .A(_294_),
    .B_N(_293_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nand3_1 _396_ (
    .A(_262_),
    .B(_287_),
    .C(_252_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__nor4_1 _397_ (
    .A(_290_),
    .B(_292_),
    .C(_251_),
    .D(_253_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__o21ai_0 _398_ (
    .A1(_249_),
    .A2(_254_),
    .B1(_207_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nor3_1 _399_ (
    .A(_289_),
    .B(_290_),
    .C(_291_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nand4_1 _400_ (
    .A(_288_),
    .B(_292_),
    .C(_252_),
    .D(_256_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__or3_1 _401_ (
    .A(_287_),
    .B(_249_),
    .C(_257_),
    .X(_258_)
  );
  sky130_fd_sc_hd__a21boi_0 _402_ (
    .A1(_255_),
    .A2(_258_),
    .B1_N(_295_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a41oi_1 _403_ (
    .A1(_298_),
    .A2(_299_),
    .A3(_210_),
    .A4(_254_),
    .B1(_206_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nand2_1 _404_ (
    .A(_206_),
    .B(_257_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__o21ai_0 _405_ (
    .A1(_249_),
    .A2(_260_),
    .B1(_295_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nor2_1 _406_ (
    .A(_259_),
    .B(_261_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__clkinv_1 _407_ (
    .A(_288_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__clkinv_1 _408_ (
    .A(_287_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__clkinv_1 _409_ (
    .A(_289_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__clkinv_1 _410_ (
    .A(_290_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__clkinv_1 _411_ (
    .A(_291_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__clkinv_1 _412_ (
    .A(_292_),
    .Y(_267_)
  );
  (* src = "ho.v:108" *)
  sky130_fd_sc_hd__dfxtp_1 _413_ (
    .CLK(clock),
    .D(_002_),
    .Q(led_fix)
  );
  (* src = "ho.v:108" *)
  sky130_fd_sc_hd__dfxtp_1 _414_ (
    .CLK(clock),
    .D(_003_),
    .Q(led_touch)
  );
  (* src = "ho.v:97" *)
  sky130_fd_sc_hd__dfxtp_1 _415_ (
    .CLK(clock),
    .D(_004_[0]),
    .Q(rdat[0])
  );
  (* src = "ho.v:97" *)
  sky130_fd_sc_hd__dfxtp_1 _416_ (
    .CLK(clock),
    .D(_004_[1]),
    .Q(rdat[1])
  );
  (* src = "ho.v:97" *)
  sky130_fd_sc_hd__dfxtp_1 _417_ (
    .CLK(clock),
    .D(_004_[2]),
    .Q(rdat[2])
  );
  (* src = "ho.v:97" *)
  sky130_fd_sc_hd__dfxtp_1 _418_ (
    .CLK(clock),
    .D(_004_[3]),
    .Q(rdat[3])
  );
  (* src = "ho.v:97" *)
  sky130_fd_sc_hd__dfxtp_1 _419_ (
    .CLK(clock),
    .D(_004_[4]),
    .Q(rdat[4])
  );
  (* src = "ho.v:97" *)
  sky130_fd_sc_hd__dfxtp_1 _420_ (
    .CLK(clock),
    .D(_004_[5]),
    .Q(rdat[5])
  );
  (* src = "ho.v:97" *)
  sky130_fd_sc_hd__dfxtp_1 _421_ (
    .CLK(clock),
    .D(_004_[6]),
    .Q(rdat[6])
  );
  (* src = "ho.v:97" *)
  sky130_fd_sc_hd__dfxtp_1 _422_ (
    .CLK(clock),
    .D(_004_[7]),
    .Q(rdat[7])
  );
  (* src = "ho.v:90" *)
  sky130_fd_sc_hd__dfxtp_1 _423_ (
    .CLK(clock),
    .D(_001_[0]),
    .Q(data_cnt[0])
  );
  (* src = "ho.v:90" *)
  sky130_fd_sc_hd__dfxtp_1 _424_ (
    .CLK(clock),
    .D(_001_[1]),
    .Q(data_cnt[1])
  );
  (* src = "ho.v:90" *)
  sky130_fd_sc_hd__dfxtp_1 _425_ (
    .CLK(clock),
    .D(_001_[2]),
    .Q(data_cnt[2])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _426_ (
    .CLK(clock),
    .D(_000_[0]),
    .Q(counter[0])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _427_ (
    .CLK(clock),
    .D(_000_[1]),
    .Q(counter[1])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _428_ (
    .CLK(clock),
    .D(_000_[2]),
    .Q(counter[2])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _429_ (
    .CLK(clock),
    .D(_000_[3]),
    .Q(counter[3])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _430_ (
    .CLK(clock),
    .D(_000_[4]),
    .Q(counter[4])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _431_ (
    .CLK(clock),
    .D(_000_[5]),
    .Q(counter[5])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _432_ (
    .CLK(clock),
    .D(_000_[6]),
    .Q(counter[6])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _433_ (
    .CLK(clock),
    .D(_000_[7]),
    .Q(counter[7])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _434_ (
    .CLK(clock),
    .D(_000_[8]),
    .Q(counter[8])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _435_ (
    .CLK(clock),
    .D(_000_[9]),
    .Q(counter[9])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _436_ (
    .CLK(clock),
    .D(_000_[10]),
    .Q(counter[10])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _437_ (
    .CLK(clock),
    .D(_000_[11]),
    .Q(counter[11])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _438_ (
    .CLK(clock),
    .D(_000_[12]),
    .Q(counter[12])
  );
  (* src = "ho.v:77" *)
  sky130_fd_sc_hd__dfxtp_1 _439_ (
    .CLK(clock),
    .D(_000_[13]),
    .Q(counter[13])
  );
  (* src = "ho.v:56" *)
  sky130_fd_sc_hd__dfxtp_1 _440_ (
    .CLK(clock),
    .D(_006_[0]),
    .Q(state[0])
  );
  (* src = "ho.v:56" *)
  sky130_fd_sc_hd__dfxtp_1 _441_ (
    .CLK(clock),
    .D(_006_[1]),
    .Q(state[1])
  );
  (* src = "ho.v:47" *)
  sky130_fd_sc_hd__dfxtp_1 _442_ (
    .CLK(clock),
    .D(_005_),
    .Q(rx_)
  );
  (* src = "ho.v:35" *)
  sky130_fd_sc_hd__dfxtp_1 _443_ (
    .CLK(clock),
    .D(_008_),
    .Q(syncff1)
  );
  (* src = "ho.v:35" *)
  sky130_fd_sc_hd__dfxtp_1 _444_ (
    .CLK(clock),
    .D(_007_),
    .Q(syncff0)
  );
  assign _298_ = state[0];
  assign _299_ = state[1];
  assign _194_ = counter[1];
  assign _189_ = counter[0];
  assign _196_ = counter[3];
  assign _195_ = counter[2];
  assign _197_ = counter[4];
  assign _198_ = counter[5];
  assign _199_ = counter[6];
  assign _200_ = counter[7];
  assign _202_ = counter[9];
  assign _201_ = counter[8];
  assign _191_ = counter[11];
  assign _190_ = counter[10];
  assign _193_ = counter[13];
  assign _192_ = counter[12];
  assign _288_ = rdat[1];
  assign _287_ = rdat[0];
  assign _004_[0] = _176_;
  assign _289_ = rdat[2];
  assign _004_[1] = _177_;
  assign _290_ = rdat[3];
  assign _004_[2] = _178_;
  assign _291_ = rdat[4];
  assign _004_[3] = _179_;
  assign _292_ = rdat[5];
  assign _004_[4] = _180_;
  assign _293_ = rdat[6];
  assign _004_[5] = _181_;
  assign _294_ = rdat[7];
  assign _004_[6] = _182_;
  assign _301_ = syncff1;
  assign _004_[7] = _183_;
  assign _203_ = data_cnt[0];
  assign _295_ = resetn;
  assign _001_[0] = _171_;
  assign _204_ = data_cnt[1];
  assign _001_[1] = _172_;
  assign _205_ = data_cnt[2];
  assign _001_[2] = _173_;
  assign _000_[0] = _157_;
  assign _000_[1] = _162_;
  assign _000_[2] = _163_;
  assign _000_[3] = _164_;
  assign _000_[4] = _165_;
  assign _000_[5] = _166_;
  assign _000_[6] = _167_;
  assign _000_[7] = _168_;
  assign _000_[8] = _169_;
  assign _000_[9] = _170_;
  assign _000_[10] = _158_;
  assign _000_[11] = _159_;
  assign _000_[12] = _160_;
  assign _000_[13] = _161_;
  assign _296_ = rx;
  assign _007_ = _187_;
  assign _297_ = rx_;
  assign _006_[0] = _185_;
  assign _006_[1] = _186_;
  assign _005_ = _184_;
  assign _300_ = syncff0;
  assign _008_ = _188_;
  assign _207_ = led_touch;
  assign _003_ = _175_;
  assign _206_ = led_fix;
  assign _002_ = _174_;
endmodule
